Repository PollBuddy/PollBuddy, pull requests merged in 2021-09, with the labels that each got.

#512 Set up the new linting system
  .github/workflows/Lint-Backend.yml
  .github/workflows/Lint-Frontend.yml
  .github/workflows/Lint.yml
Labels: bug, frontend, backend

#515 fixed link
  CONTRIBUTING.md
Labels: bug, documentation

#517 Fixed CI-PR via a different version specifier
  .github/workflows/CI-PullRequest.yml
Labels: bug
